Gemfile
Gemfile.lock
app/assets/stylesheets/custom.css
app/controllers/application_controller.rb
app/helpers/devise_helper.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/test/index.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/locales/en.yml
config/routes.rb
db/migrate/20150303060548_devise_create_users.rb
db/schema.rb
test/fixtures/users.yml
test/unit/user_test.rb

Added Devise and appropriate views. Integrated Bootstrap into Devise views.

Devise and some html for users.

---

app/views/layouts/application.html.erb

Minor fix for name. Unworthy of review.

Minor fix.

---

app/views/devise/registrations/new.html.erb
config/locales/en.yml

Minor fixes.

---

config/locales/en.yml

More minor fixes.

---

app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
config/locales/en.yml

More prettifying. Put all the login-related pages in pretty little wells.

Bootstrap updates.

---

Gemfile
Gemfile.lock
config/application.rb

Modified gems for Heroku deployment. [Here's](http://khanburmese.herokuapp.com/users/sign_in) a link to the deployment.

Configuration for Heroku deployment.

---

app/assets/stylesheets/custom.css
app/views/devise/shared/_social.html.erb
app/views/test/index.html.erb

See diff for details.
Reviewer: @nalnaji @jonathanshum

Minor styling fixes.

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/views/home/index.html.erb
config/routes.rb

Added a home page with filler material.
When user is not signed in and accesses a protected page, authentication will redirect him back to that page.
TODO (Shum): Flesh out that home page.

Login redirection.

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/ability.rb
db/migrate/20150306014926_add_admin_to_users.rb
db/schema.rb

Every "User" now has an attribute called "admin" of boolean type. If true, the user is an admin and has certain abilities. 
To monitor "Admin" vs "User" abilities, we are using "CanCan". Abilities can be added and changed in: app/models/ability.rb

added administrative functionality

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20150306015404_create_rails_admin_histories_table.rb
db/schema.rb

Route is at `/admin`. Currently no error message if user has no permissions.
TODO (Darren): Add an error message for non-admins.

Added rails_admin gem and integrated with CanCan.

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/helpers/devise_helper.rb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
config/initializers/rails_admin.rb

Self-explanatory. Also modified some flash messages. We should use `:alert` and `:notice` for all flash message keys. Could also possibly add `:warning`.

Added error message for rails_admin page.

---

Gemfile
Gemfile.lock
features/admin_path.feature
features/login.feature
features/signup.feature
features/step_definitions/web_steps.rb
features/support/env.rb
features/support/paths.rb
spec/controllers/test_controller_spec.rb
spec/factories.rb
spec/models/ability_spec.rb
spec/models/identity_spec.rb
spec/models/user_spec.rb
spec/spec_helper.rb
spec/support/controller_macros.rb

90% Coverage.

---

db/seeds.rb
db/seeds/development.rb
db/seeds/production.rb

Added a seed for the first administrator. Make sure to delete this account or change its password following `rake db:seed`.

Solution for first administrator account.

---

features/step_definitions/login_steps.rb
features/step_definitions/user_steps.rb
features/step_definitions/web_steps.rb

Side note: when I run cucumber, I only get about 68% coverage. For some reason my find_for_oauth method is being called, but not used.

separate cucumber steps into separate files

---

app/controllers/application_controller.rb
app/models/ability.rb
app/models/user.rb
config/initializers/rails_admin.rb
config/locales/en.yml
db/migrate/20150307011907_add_role_to_users.rb
db/migrate/20150307011950_remove_admin_from_users.rb
db/schema.rb
features/admin_path.feature
features/step_definitions/user_steps.rb
spec/factories.rb

RailsAdmin is now really omnipotent.
List of [related] features:
* Moved RailsAdmin authorization to CanCan.
* Killed admin attribute and replaced with role.
* Updated tests to properly see roles.
Reviewer: @nalnaji @delicioustoast

RailsAdmin proper integration.

---

db/seeds/development.rb
db/seeds/production.rb

Updated seed files according to new user roles.

Updated seed files.

---

.travis.yml
Gemfile
Gemfile.lock
config/cucumber.yml

Rake + .travis.yml
Might need to edit config/cucumber.yml to stop email notifications

Added rake and travis ci file

---

app/views/layouts/application.html.erb

This branch has been sitting here for a while, so let's just merge it in. Made error divs "dismissible" with an x button in the top right.

Made errors dismissible.

---

app/models/video.rb
db/migrate/20150312215548_create_videos.rb
db/schema.rb

Hey guys,
These are all up for debate obviously. Let me know if I missed anything and even feel free to update my branch/PR yourselves. 
Reviewers: @DarryQueen, @nishadsingh1, @bwasmith

Video representation v-1.0

---

app/models/user.rb
db/migrate/20150312234511_add_personal_atts_to_user.rb
db/schema.rb

Basically just added some attributes we discussed about on Sunday.
Feel free to rip me apart.
@DarryQueen @bwasmith  @nishadsingh1

Updating User model to have more personal fields

---

app/assets/javascripts/ajax-video-search.js
app/assets/stylesheets/new-elements.css
app/controllers/videos_controller.rb
app/models/video.rb
app/views/videos/_video_list.html.erb
app/views/videos/index.html.erb
app/views/videos/index.js.erb
config/routes.rb

Probably should have been more than just a single commit. Searching should be more well-defined and fleshed out, but the UI side is fine now.

AJAX video searching.

---

config/initializers/devise.rb

fixed keys propblem for gsis

---

app/controllers/application_controller.rb

As title says. Cute little error message, albeit crappily coded.

Raises error if API keys not set in development.

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/helpers/devise_helper.rb
app/views/layouts/application.html.erb

Supports adding multiple flash messages by storing them in an array and rendering them dynamically.

Flash cleanup.

---

app/helpers/devise_helper.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/passwords/edit.html.erb
config/locales/devise.en.yml
config/locales/en.yml

Customized the reset password and resend confirmation views to fit our Bootstrap theme.
Reviewer: @nalnaji @jonathanshum

Customized Devise views.

---

app/assets/stylesheets/jquery-ui-custom.min.css

Pretty trivial. Bigger PR coming up soon.

Fixed a stupid routing error.

---

.travis.yml
Gemfile
Gemfile.lock
app/views/videos/index.html.erb
features/step_definitions/login_steps.rb
features/step_definitions/video_steps.rb
features/support/paths.rb
features/video_search.feature

Tests for video searching. Uses Selenium for testing AJAX calls.
Minor update to the video view to add an ID field. Necessary for Cucumber to find input.

Javascript tests.

---

app/models/ability.rb
features/step_definitions/video_steps.rb
features/video_search.feature
features/video_search_admin.feature
features/video_search_volunteer.feature

Various cucumber tests for prioritization, as well as a minor bugfix for a previous test. We're back up to 90% code coverage!
Also a bugfix for administrator permissions in CanCan.

Cucumber tests.

---

app/models/translation.rb
app/models/user.rb
app/models/video.rb
db/migrate/20150330225258_create_translations.rb
db/schema.rb

Added the Translation migration and model. Video and User now have access to translations and each other through translations.
reviewer: @DarryQueen

Translation migration

---

app/models/translation.rb
spec/factories.rb
spec/models/translation_spec.rb
spec/models/user_spec.rb
spec/models/video_spec.rb

Added tests that ensure that Translations are associated with a video, that Users can access their translations and videos through them, and that Videos can access their translations and users through them.
reviewer: @DarryQueen

Rspec that tests interactions using the Translation model.

---

README.md

It's so cute!
Reviewer: @nalnaji @nishadsingh1

Added cute badges to README.md.

---

app/assets/stylesheets/custom.css
app/views/layouts/application.html.erb

Separated dropdown links from the nav bar. Links should appear directly below nav bar for screen widths under 768 px.

Fixed navigation dropdown for small screens in different browsers

---

app/assets/stylesheets/videos.css
app/views/home/dashboard.html.erb
app/views/videos/index.html.erb
app/views/videos/index/_video_list.html.erb
app/views/videos/index/_video_row.html.erb
app/views/videos/show.html.erb
app/views/videos/show/_actions.html.erb
app/views/videos/show/_video_frame.html.erb

Video list includes more information: Subject, Time, Status. Modal button on show view for unassigning videos now has rounded corners as well. Embedded video footer replaced with subject and duration tags rather than status.

Updated video list & show UI

---

app/assets/stylesheets/custom.css

It's really trivial. Just fixes spacing for non-starred videos in the listing.
Reviewer: @jonathanshum

Trivial UI fix.

---

app/assets/stylesheets/general-elements.css
app/controllers/files_controller.rb
app/controllers/videos_controller.rb
app/models/ability.rb
app/models/translation.rb
app/models/video.rb
app/views/videos/show.html.erb
app/views/videos/show/_actions.html.erb
app/views/videos/show/_translations_frame.html.erb
config/routes.rb
db/migrate/20150406195923_add_timestamps_to_translations.rb
db/schema.rb

Added a dynamic translations panel to the video show page. It'll show only the completed translations. No review system yet, but otherwise this video page is near complete.

Dynamic translations panel.

---

app/assets/stylesheets/custom.css
app/assets/stylesheets/general-elements.css
app/views/preview/profile.html.erb

Added modules for profile, about me, assigned videos, reviewed videos, and approved videos.

Profile prototype

---

app/models/user.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/registrations/new.html.erb
db/migrate/20150406230646_add_name_to_user.rb
db/schema.rb
spec/models/user_spec.rb

Name fields for users. Even pulls from Facebook and Google!
Reviewer: @nalnaji @jonathanshum

User names.

---

app/assets/stylesheets/new-elements.css
app/controllers/videos_controller.rb
app/models/ability.rb
app/models/video.rb
app/views/videos/import.html.erb
config/application.rb
config/routes.rb
db/migrate/20150408010213_add_duration_to_videos.rb
db/schema.rb
lib/modules/YoutubeReader.rb
public/video/template.csv

The code's a bit messy, could probably use some cleaning up.
The only important item from the CSV file is the YouTube ID. Maybe we could just collect the ID's from the CSV then pull the rest of the data (e.g. title, description) from YouTube itself? Or maybe it doesn't really matter.
import.html.erb is definitely a work on progress.
I'll add tests later.
Reviewer: @DarryQueen @nalnaji

Handles uploading of CSV files

---

app/controllers/videos_controller.rb
app/views/videos/show.html.erb
app/views/videos/show/_contributor_row.html.erb
app/views/videos/show/_contributors_frame.html.erb

Hey guys, 
I refactored Shum's HTML into partial for prettiness.
I also made the contributors panel actually functional so it's not just fake data anymore.
Something I need to add: How many contributors should we show? It's not limited right now.
REVIEWERS: @DarryQueen @jonathanshum @nishadsingh1

Contributors Panel Feature

---

app/assets/stylesheets/custom.css
app/controllers/home_controller.rb
app/controllers/preview_controller.rb
app/helpers/application_helper.rb
app/models/video.rb
app/views/home/dashboard.html.erb
app/views/home/dashboard/_accomplishments_frame.html.erb
app/views/home/dashboard/_goals_frame.html.erb
app/views/home/dashboard/_rankings_frame.html.erb
app/views/preview/dashboard.html.erb
app/views/preview/index.html.erb
app/views/videos/index.js.erb
app/views/videos/index/_video_row.html.erb
app/views/videos/index/_videos_list.html.erb
app/views/videos/index/_videos_table.html.erb

Updated dashboard to be dynamic. Each of the panes has mutually exclusive videos, meaning that if something shows up as assigned, it won't show up in priority videos.
TODO:
* Add "collaborative weekly goals." This should probably be turned into more of a "group achievements" pane.
* Add rankings. As usual. This should be easier since we have point metrics.

Dashboard updates.

---

app/models/ability.rb
config/locales/en.yml

Updated error messages and removed superadmin permissions. We can add them in later when the site rolls into real production.

Truly trivial commits.

---

app/mailers/user_mailer.rb

Trivial bug fix for mailer. Works in development, fix is purely for Heroku production server.

Bugfix for mailer.

---

features/step_definitions/web_steps.rb

Self-explanatory. I wonder if our CodeClimate score goes up.
Reviewer: @nalnaji @delicioustoast

Dried out some code in web steps (though it could be nicer).

---

app/assets/javascripts/videos.js
app/assets/stylesheets/vote.sass
app/views/videos/index.js.erb
app/views/videos/translations/_translation_row.html.erb

Various UI changes and code updates. Minor refactoring and added back the voting stylesheets, which were deleted in a previous CSS overhaul.
Reviewer: @jonathanshum

Various UI commits.

---

app/assets/stylesheets/users.sass
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/preview/dashboard.html.erb
app/views/users/show.html.erb
app/views/users/show/_profile_frame.html.erb

Mostly untouched devise html pages.

HTML & CSS changes for general panels and elements throughout the site

---

app/assets/javascripts/videos.js
app/views/videos/show/_actions.html.erb
app/views/videos/translations/_translations_frame.html.erb

Now the review button actually does something! Adds a little tooltip directing users to the translations frame.

Added hover to review button.

---

app/models/video.rb

Workaround but not solution to Postgres database queries. Uses lowercase searching. Addresses https://github.com/DarryQueen/Khan-Burmese/issues/59.
Reviewer: @nalnaji @bwasmith @jonathanshum

Temporary fix to case-sensitive search issue.

---

app/assets/javascripts/users.js
app/assets/stylesheets/dashboard.sass
app/assets/stylesheets/users.sass
app/controllers/users_controller.rb
app/models/user.rb
app/views/home/dashboard/_accomplishments_frame.html.erb
app/views/home/dashboard/_rankings_frame.html.erb
app/views/users/leaderboard.html.erb
app/views/users/leaderboard.js.erb
app/views/users/leaderboard/_leader_frame.html.erb
app/views/users/leaderboard/_leader_row.html.erb
app/views/users/leaderboard/_leaders_frame.html.erb
app/views/videos/index.js.erb
config/routes.rb

Added leaderboard feature.
Shum, let me know how I can improve the UI.
reviewer: @jonathanshum

Leaderboard

---

app/assets/stylesheets/users.sass
app/views/users/show/_profile_frame.html.erb
app/views/users/show/_user_field_row.html.erb

Updates to user profile page view. Fix overflow issues with long fields. Also cleaned up user fields into nicer partials.

User profile page updates.

---

app/controllers/home_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
spec/models/user_spec.rb

Incorrectly grabbing assigned videos for users. Bugfix for issue.

Bugfix for user videos.

---

app/assets/stylesheets/navbar.sass
app/views/home/dashboard.html.erb
app/views/layouts/application.html.erb
app/views/videos/show/_translate_frame.html.erb

1. Added dynamic links to videos and leaderboard
2. Flipped the ordering for recently translated videos and top priority videos on the dashboard
3. Amara link opens in a new window now

Navbar and customer preferences

---

spec/controllers/translations_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/helpers/video_helper_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/translation_spec.rb
spec/models/user_spec.rb
spec/models/video_spec.rb

Rspec tests on controllers, models, and user mailer.
reviewer: @DarryQueen @nalnaji

Tests for controllers and models associated with leaderboard

---

app/assets/stylesheets/videos.sass
app/controllers/videos_controller.rb
app/models/video.rb
app/views/videos/new.html.erb
config/locales/en.yml
lib/modules/YoutubeReader.rb

Will write tests later.
Go to /videos/new to import a new video
Youtube ID and subject are mandatory fields
Reviewer: @DarryQueen @nalnaji @jonathanshum

Import individual Youtube videos via ID

---

app/assets/stylesheets/videos.sass
app/controllers/videos_controller.rb
app/models/ability.rb
app/models/video.rb
app/views/videos/edit.html.erb
app/views/videos/show/_video_frame.html.erb

Adds paths for administrators to edit videos. Fairly self-explanatory.
Reviewer: @nalnaji @delicioustoast

Editing videos.

---

app/assets/javascripts/videos.js
app/assets/stylesheets/videos.sass
app/views/videos/index/_videos_list.html.erb

Self-explanatory. Cute little spinner for when search results pending.

Added feedback for search duration.

---

app/views/videos/show/_video_frame.html.erb

Edit button appears on show page even for non-admins. Bugfix for issue.

Bugfix for normal volunteers and edit button.

---

app/controllers/videos_controller.rb
app/models/video.rb
app/views/videos/show.html.erb
app/views/videos/show/_similar_videos_frame.html.erb
app/views/videos/show/_similar_videos_row.html.erb

The box on the videos/show page finally shows us similar vids :)

added similar videos functionality

---

app/controllers/users_controller.rb
app/controllers/videos_controller.rb
app/models/ability.rb
app/models/video.rb
app/views/users/show/_about_frame.html.erb
app/views/users/show/_profile_frame.html.erb
app/views/users/show/_user_field_row.html.erb
app/views/videos/edit.html.erb
app/views/videos/edit/_destroy_modal.html.erb
app/views/videos/show/_video_frame.html.erb

Allows administrators to destroy videos. Includes a destroy button on the edit page.

Destroy video path.

---

app/controllers/home_controller.rb
app/views/home/dashboard.html.erb
app/views/home/dashboard/_leader_row.html.erb
app/views/home/dashboard/_rankings_frame.html.erb

Shows the top three translators for the week in the dashboard. Displays their name and the number of points they received (location info takes up too much space relative to the profile pic).
Reviewer: @DarryQueen @nalnaji

nonstatic leaderboard for dashboard

---

app/assets/stylesheets/dashboard.sass
app/views/home/dashboard.html.erb
app/views/home/dashboard/_rankings_frame.html.erb
app/views/videos/index/_videos_list.html.erb

Panel headings are now clickable if they have title links.
Reviewer: @jonathanshum

Stylized panel title links.

---

app/views/preview/admin-panel.html.erb
app/views/preview/index.html.erb

Preview admin page to
1) Add videos
2) Show stats about the site

Admin panel preview page

---

app/views/layouts/application.html.erb
app/views/videos/import.html.erb
app/views/videos/new.html.erb

1) Custom request for KA Myanmar vs Khan Academy Myanmar
2) Consistent import and new videos views

Brand fix and adding videos

---

app/controllers/home_controller.rb
app/models/ability.rb
app/views/home/admin_dashboard.html.erb
app/views/layouts/application.html.erb
config/routes.rb

Added an administrator page to add videos and import a list of video.

Administrator page.

---

app/assets/stylesheets/users.sass
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/edit/_destroy_modal.html.erb
app/views/users/show.html.erb
app/views/users/show/_profile_frame.html.erb
config/routes.rb

Can delete users (including oneself) as an admin/superadmin.
Not sure how translations will be affected once its user is deleted (can't test that locally for whatever reason).
Reviewers: @DarryQueen @nalnaji

delete users feature

---

app/assets/stylesheets/videos.sass
app/controllers/translations_controller.rb
app/models/translation.rb
app/views/videos/show/_translate_frame.html.erb
config/routes.rb
features/video_translation.feature
spec/controllers/translations_controller_spec.rb

As per client's request, removed feature to directly upload SRT file.
Reviewer: @jonathanshum @delicioustoast

Removed uploading SRT file from UI.

---

features/destroy_user.feature
features/step_definitions/user_steps.rb
features/support/paths.rb

Added a test to destroy a user, and modified one of the previous cucumber definitions so that it can be applied to the delete button.

Test destroy user

---

spec/controllers/users_controller_spec.rb
spec/controllers/videos_controller_spec.rb
spec/models/translation_spec.rb

Should be at least 90% test coverage.
Reviewers: @DarryQueen @nalnaji

gimme dat test coverage

---

app/views/home/dashboard/_leader_row.html.erb
app/views/videos/show/_contributor_row.html.erb

User rows are unbolded and have no link.
Reviewer: @jonathanshum

Made user rows more consistent.

---

app/assets/stylesheets/users.sass
app/controllers/users_controller.rb
app/models/ability.rb
app/models/user.rb
app/views/users/edit/_roles_modal.html.erb
app/views/users/show.html.erb
app/views/videos/index.html.erb
config/locales/en.yml
config/routes.rb

Makes a volunteer an admin. Does nothing for those already admins/superadmins.
Reviewers: @DarryQueen @nalnaji

Promote a volunteer to an admin

---

app/assets/stylesheets/videos.sass
app/controllers/videos_controller.rb
app/models/video.rb
app/views/videos/import.html.erb
features/assets/doc.csv
features/destroy_user.feature
features/import_videos.feature
features/step_definitions/web_steps.rb

Video importing now runs completely regardless of errors. Also runs asynchronously and displays a `session` message on completion, on the import page.
Reviewer: @nalnaji @delicioustoast

Asynchronous video uploading.

---

app/assets/stylesheets/general/module.sass
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/home/dashboard.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb

- Dynamic index page
- Consistent green login buttons
- Meta tag for mobile devices

Mobile friendly pages

---

README.md

Self-explanatory. For visual purposes only.

Update to README.md.

---

Gemfile
Gemfile.lock
spec/controllers/home_controller_spec.rb
spec/controllers/translations_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/controllers/videos_controller_spec.rb
spec/factories.rb
spec/mailers/user_mailer_spec.rb
spec/models/ability_spec.rb
spec/models/identity_spec.rb
spec/models/translation_spec.rb
spec/models/user_spec.rb
spec/models/video_spec.rb
spec/support/controller_macros.rb

Get rid of FactoryGirl.

---

.travis.yml
Gemfile
Gemfile.lock
Procfile
app/controllers/videos_controller.rb
app/models/import.rb
app/models/video.rb
app/views/videos/import.html.erb
app/workers/import_video_worker.rb
db/migrate/20160427222453_create_imports.rb
db/schema.rb
features/import_videos.feature

Is now smoother and more reliable for video importing with Sidekiq. Seems to have some issues with SQLite3 and database locking, but I'll assume that's only local for now.
TODO: Add some sort of "pending" status. Right now, imports are successful by default.

Sidekiq jobs.
